import {NRC} from '@/lib/models'

export const REAL_NRC_DATA:NRC[] = [
  {
    "regionCode": "1-၁-၁",
    "townships": [
      "BaKaNa-ဗကန-ဗကန",
      "BaMaNa-ဘမန-ဘမန",
      "PaMaNa-ပမန-ပမန",
      "AhTaNa-အတန-အတန",
      "MaTaNa-မတန-မတန",
      "KhaPhaNa-ခဖန-ခဖန",
      "TaNaNa-တနန-တနန",
      "PhaKaNa-ဖကန-ဖကန",
      "KaMaNa-ကမန-ကမန",
      "KhaLaPha-ခလဖ-ခလဖ",
      "MaKhaBa-မခဘ-မခဘ",
      "MaSaNa-မစန-မစန",
      "MaKaTa-မကတ-မကတ",
      "MaNyaNa-မညန-မညန",
      "HaPaNa-ဟပန-ဟပန",
      "MaKaTha-မကသ-မကသ",
      "MaMaNa-မမန-မမန",
      "MaKaNa-မကန-မကန",
      "SaKaNa-စကန-စကန",
      "KaMaTa-ကမတ-ကမတ",
      "SaBaTa-ဆဘတ-ဆဘတ",
      "SaPaBa-စပဘ-စပဘ",
      "MaGaDa-မဂဒ-မဂဒ",
      "AhGaYa-အဂယ-အဂယ",
      "NaMaNa-နမန-နမန",
      "PaTaAh-ပတအ-ပတအ",
      "YaKaNa-ရကန-ရကန",
      "SaBaNa-ဆဘန-ဆဘန",
      "SaLaNa-ဆလန-ဆလန",
      "WaMaNa-ဝမန-ဝမန",
      "HsaDaNa-ဆဒန-ဆဒန",
      "RaBaYa-ရဗယ-ရဗယ",
      "LaGaNa-လဂန-လဂန",
      "PaNaDa-ပနဒ-ပနဒ",
      "KhaBaDa-ခဘဒ-ခဘဒ",
      "HsaPaBa-ဆပဘ-ဆပဘ",
      "DaPhaYa-ဒဖယ-ဒဖယ",
      "MaLaNa-မလန-မလန"
    ]
  },
  {
    "regionCode": "2-၂-၂",
    "townships": [
      "BaLaKha-ဘလခ-ဘလခ",
      "DaMaSa-ဒမဆ-ဒမဆ",
      "SaSaNa-စစန-စစန",
      "HtaTaPa-ထတပ-ထတပ",
      "KhaSaNa-ခစန-ခစန",
      "PhaLaSa-ဖလဆ-ဖလဆ",
      "PhaYaSa-ဖရဆ-ဖရဆ",
      "LaKaNa-လကန-လကန",
      "MaSaNa-မဆန-မဆန",
      "YaTaNa-ရတန-ရတန",
      "HpaHsaNa-ဖဆန-ဖဆန",
      "RaThaNa-ရသန-ရသန"
    ]
  },
  {
    "regionCode": "3-၃-၃",
    "townships": [
      "LaBaNa-လဘန-လဘန",
      "PaKaNa-ပကန-ပကန",
      "YaYaTha-ရရသ-ရရသ",
      "PhaAhNa-ဖအန-ဖအန",
      "BaAhNa-ဘအန-ဘအန",
      "PhaPaNa-ဖပန-ဖပန",
      "KaMaMa-ကမမ-ကမမ",
      "KaKaYa-ကကရ-ကကရ",
      "KaDaNa-ကဒန-ကဒန",
      "KaSaKa-ကဆက-ကဆက",
      "MaWaTa-မဝတ-မဝတ",
      "SaKaLa-စကလ-စကလ",
      "MaSaLa-မဆလ-မဆလ",
      "KaTaKha-ကတခ-ကတခ",
      "WaLaMa-ဝလမ-ဝလမ",
      "BaGaLa-ဘဂလ-ဘဂလ",
      "LaThaNa-လသန-လသန",
      "ThaTaNa-သတန-သတန",
      "ThaTaKa-သတက-သတက",
      "BaThaHsa-ဘသဆ-ဘသဆ"
    ]
  },
  {
    "regionCode": "4-၄-၄",
    "townships": [
      "HpaLaNa-ဖလန-ဖလန",
      "HaKhaNa-ဟခန-ဟခန",
      "KaPaLa-ကပလ-ကပလ",
      "MaTaPa-မတပ-မတပ",
      "MaTaNa-မတန-မတန",
      "PaLaWa-ပလဝ-ပလဝ",
      "TaTaNa-တတန-တတန",
      "HtaTaLa-ထတလ-ထတလ",
      "TaZaNa-တဇန-တဇန",
      "RaKhaDa-ရခဒ-ရခဒ",
      "RaZaNa-ရဇန-ရဇန",
      "HsaMaNa-ဆမန-ဆမန",
      "KaKhaNa-ကခန-ကခန"
    ]
  },
  {
    "regionCode": "5-၅-၅",
    "townships": [
      "AhYaTa-အရတ-အရတ",
      "BaMaNa-ဗမန-ဗမန",
      "BaTaLa-ဘတလ-ဘတလ",
      "KhaAuNa-ခဥန-ခဥန",
      "KhaTaNa-ခတန-ခတန",
      "HaMaLa-ဟမလ-ဟမလ",
      "AhTaNa-အတန-အတန",
      "KaLaNa-ကလန-ကလန",
      "KaLaHta-ကလထ-ကလထ",
      "KaLaWa-ကလဝ-ကလဝ",
      "KaBaLa-ကဘလ-ကဘလ",
      "AhHtaNa-အထန-အထန",
      "KaNaNa-ကနန-ကနန",
      "KaThaNa-ကသန-ကသန",
      "KaLaTa-ကလတ-ကလတ",
      "KaSaLa-ကဆလ-ကဆလ",
      "HtaPaKha-ထပခ-ထပခ",
      "LaHaNa-လဟန-လဟန",
      "LaYaNa-လရန-လရန",
      "MaPaLa-မပလ-မပလ",
      "SaMaYa-ဆမရ-ဆမရ",
      "MaLaNa-မလန-မလန",
      "MaKaNa-မကန-မကန",
      "MaYaNa-မရန-မရန",
      "MaMaNa-မမန-မမန",
      "DaHaNa-ဒဟန-ဒဟန",
      "NaYaNa-နယန-နယန",
      "PaSaNa-ပဆန-ပဆန",
      "PaLaNa-ပလန-ပလန",
      "PhaPaNa-ဖပန-ဖပန",
      "PaLaBa-ပလဘ-ပလဘ",
      "SaKaNa-စကန-စကန",
      "SaLaKa-ဆလက-ဆလက",
      "KaMaNa-ကမန-ကမန",
      "YaBaNa-ရဘန-ရဘန",
      "DaPaYa-ဒပယ-ဒပယ",
      "TaMaNa-တမန-တမန",
      "MaThaNa-မသန-မသန",
      "TaSaNa-တဆန-တဆန",
      "HtaKhaNa-ထခန-ထခန",
      "KaLaTha-ကလသ-ကလသ",
      "NgaSaNa-ငစန-ငစန",
      "TaAuNa-တဥန-တဥန",
      "DaKaNa-ဓကန-ဓကန",
      "AhMaZa-အမဇ-အမဇ",
      "WaLaNa-ဝလန-ဝလန",
      "WaThaNa-ဝသန-ဝသန",
      "YaAuNa-ရဥန-ရဥန",
      "YaMaPa-ယမပ-ယမပ",
      "MaMaTa-မမတ-မမတ",
      "KhaUTa-ခဥတ-ခဥတ",
      "KhaPaNa-ခပန-ခပန"
    ]
  },
  {
    "regionCode": "6-၆-၆",
    "townships": [
      "BaPaNa-ဘပန-ဘပန",
      "HtaWaNa-ထဝန-ထဝန",
      "AhMaYa-အမရ-အမရ",
      "KaYaYa-ကရရ-ကရရ",
      "KaPaNa-ကပန-ကပန",
      "KaThaMa-ကသမ-ကသမ",
      "HaThaTa-ဟသတ-ဟသတ",
      "KhaMaKa-ခမက-ခမက",
      "MaMaLa-မမလ-မမလ",
      "KaThaNa-ကသန-ကသန",
      "KaSaNa-ကစန-ကစန",
      "MaAhNa-မအန-မအန",
      "LaLaNa-လလန-လလန",
      "MaMaNa-မမန-မမန",
      "MaAhYa-မအရ-မအရ",
      "PhaLaNa-ပလန-ပလန",
      "TaThaYa-တသရ-တသရ",
      "ThaYaKha-သရခ-သရခ",
      "YaPhaNa-ရဖန-ရဖန",
      "KaLaA-ကလအ-ကလအ",
      "PaLaTa-ပလတ-ပလတ",
      "PaKaMa-ပကမ-ပကမ"
    ]
  },
  {
    "regionCode": "7-၇-၇",
    "townships": [
      "PaKhaNa-ပခန-ပခန",
      "MaWaTa-မဝတ-မဝတ",
      "DaAuNa-ဒဥန-ဒဥန",
      "KaPaKa-ကပက-ကပက",
      "HtaTaPa-ထတပ-ထတပ",
      "KaWaNa-ကဝန-ကဝန",
      "KaKaNa-ကကန-ကကန",
      "KaTaKha-ကတခ-ကတခ",
      "KaTaNa-ကတန-ကတန",
      "LaPaTa-လပတ-လပတ",
      "MaLaNa-မလန-မလန",
      "MaNyaNa-မညန-မညန",
      "NaTaLa-နတလ-နတလ",
      "NyaLaPa-ညလပ-ညလပ",
      "AhPhaNa-အဖန-အဖန",
      "AhTaNa-အတန-အတန",
      "PaTaNa-ပတန-ပတန",
      "PaKhaTa-ပခတ-ပခတ",
      "PaTaTa-ပတတ-ပတတ",
      "PhaMaNa-ဖမန-ဖမန",
      "PaSaTa-ပစတ-ပစတ",
      "PaMaNa-ပမန-ပမန",
      "YaTaNa-ရတန-ရတန",
      "YaKaNa-ရကန-ရကန",
      "TaNgaNa-တငန-တငန",
      "ThaNaPa-သနပ-သနပ",
      "ThaWaTa-သဝတ-သဝတ",
      "ThaKaNa-သကန-သကန",
      "WaMaNa-ဝမန-ဝမန",
      "YaTaYa-ရတရ-ရတရ",
      "ZaKaNa-ဇကန-ဇကန",
      "BaThaYa-ဘသရ-ဘသရ"
    ]
  },
  {
    "regionCode": "8-၈-၈",
    "townships": [
      "AhLaNa-အလန-အလန",
      "MaHtaNa-မထန-မထန",
      "KhaMaNa-ခမန-ခမန",
      "BaKaLa-ဘကလ-ဘကလ",
      "GaGaNa-ဂဂန-ဂဂန",
      "KaMaNa-ကမန-ကမန",
      "MaKaNa-မကန-မကန",
      "MaBaNa-မဘန-မဘန",
      "MaTaNa-မတန-မတန",
      "MaLaNa-မလန-မလန",
      "MaMaNa-မမန-မမန",
      "MaThaNa-မသန-မသန",
      "NaMaNa-နမန-နမန",
      "NgaPhaNa-ငဖန-ငဖန",
      "PaKhaKa-ပခက-ပခက",
      "PaMaNa-ပမန-ပမန",
      "PaPhaNa-ပဖန-ပဖန",
      "SaLaNa-စလန-စလန",
      "KaHtaNa-ကထန-ကထန",
      "SaPhaNa-ဆဖန-ဆဖန",
      "SaTaYa-စတရ-စတရ",
      "SaPaWa-ဆပဝ-ဆပဝ",
      "MaYaSa-မရဆ-မရဆ",
      "MaGaDa-မဂဒ-မဂဒ",
      "MaHtaLa-မထလ-မထလ",
      "TaTaKa-တတက-တတက",
      "ThaYaNa-သရန-သရန",
      "HtaLaNa-ထလန-ထလန",
      "YaNaKha-ရနခ-ရနခ",
      "YaSaKa-ရစက-ရစက",
      "HsaMaNa-ဆမန-ဆမန"
    ]
  },
  {
    "regionCode": "9-၉-၉",
    "townships": [
      "AhMaYa-အမရ-အမရ",
      "KhaMaSa-ခမစ-ခမစ",
      "KhaMaKha-ခမခ-ခမခ",
      "AhYaTa-အရတ-အရတ",
      "ThaTaYa-သတရ-သတရ",
      "KhaMaZa-ခမဇ-ခမဇ",
      "NaNaMa-နနမ-နနမ",
      "PaKhaMa-ပခမ-ပခမ",
      "KaMaNa-ကမန-ကမန",
      "AhMaZa-အမဇ-အမဇ",
      "MaNaMa-မနမ-မနမ",
      "KhaAhZa-ခအဇ-ခအဇ",
      "KhaMaTha-ခမသ-ခမသ",
      "KaPaTa-ကပတ-ကပတ",
      "KhaMaNa-ခမန-ခမန",
      "KaSaNa-ကဆန-ကဆန",
      "NaTaKa-နတက-နတက",
      "SaKaTa-စကတ-စကတ",
      "MaSaNa-မစန-မစန",
      "LaKaNa-လကန-လကန",
      "YaAuNa-ရဥန-ရဥန",
      "MaYaTa-မရတ-မရတ",
      "MaTaNa-မတန-မတန",
      "MaTaYa-မတရ-မတရ",
      "MaHaMa-မဟမ-မဟမ",
      "MaLaNa-မလန-မလန",
      "MaHtaLa-မထလ-မထလ",
      "MaKaNa-မကန-မကန",
      "MaKhaNa-မခန-မခန",
      "MaThaNa-မသန-မသန",
      "NaMaNa-နမန-နမန",
      "MaTaLa-မတလ-မတလ",
      "NaHtaKa-နထက-နထက",
      "NgaZaNa-ငဇန-ငဇန",
      "NyaAuNa-ညဥန-ညဥန",
      "AhKhaNa-အခန-အခန",
      "PaThaKa-ပသက-ပသက",
      "PaBaNa-ပဘန-ပဘန",
      "PaKaKha-ပကခ-ပကခ",
      "AhMaBa-အမဘ-အမဘ",
      "AhSaNa-အစန-အစန",
      "KhaMaMa-ခမမ-ခမမ",
      "MaKaKha-မကခ-မကခ",
      "MaNaTa-မနတ-မနတ",
      "MaYaMa-မရမ-မရမ",
      "PaKhaKa-ပခက-ပခက",
      "ThaWaNa-သဝန-သဝန",
      "PaAuLa-ပဥလ-ပဥလ",
      "MaMaNa-မမန-မမန",
      "SaKaNa-စကန-စကန",
      "TaTaAu-တတဥ-တတဥ",
      "TaThaNa-တသန-တသန",
      "ThaPaKa-သပက-သပက",
      "ThaSaNa-သစန-သစန",
      "WaTaNa-ဝတန-ဝတန",
      "YaMaTha-ရမသ-ရမသ",
      "DaKhaTha-ဒခသ-ဒခသ",
      "LaWaNa-လဝန-လဝန",
      "AuTaTha-ဥတသ-ဥတသ",
      "PaBaTha-ပဗသ-ပဗသ",
      "PaMaNa-ပမန-ပမန",
      "TaKaNa-တကန-တကန",
      "ZaBaTha-ဇဗသ-ဇဗသ",
      "ZaYaTha-ဇယသ-ဇယသ",
      "TaKaTa-တကတ-တကတ",
      "NgaThaRa-ငသရ-ငသရ"
    ]
  },
  {
    "regionCode": "10-၁၀-၁၀",
    "townships": [
      "BaLaNa-ဘလန-ဘလန",
      "KhaSaNa-ခဆန-ခဆန",
      "KaMaYa-ကမရ-ကမရ",
      "BaAhNa-ဘအန-ဘအန",
      "KaHtaNa-ကထန-ကထန",
      "HtaHtaNa-ထထန-ထထန",
      "KaMaLa-ကမလ-ကမလ",
      "PhaPaNa-ဖပန-ဖပန",
      "MaSaNa-မစန-မစန",
      "MaLaMa-မလမ-မလမ",
      "MaDaNa-မဒန-မဒန",
      "PaMaNa-ပမန-ပမန",
      "ThaPhaYa-သဖရ-သဖရ",
      "ThaHtaNa-သထန-သထန",
      "KhaZaNa-ခဇန-ခဇန",
      "LaMaNa-လမန-လမန",
      "YaMaNa-ရမန-ရမန"
    ]
  },
  {
    "regionCode": "11-၁၁-၁၁",
    "townships": [
      "AhMaNa-အမန-အမန",
      "BaThaTa-ဘသတ-ဘသတ",
      "GaMaNa-ဂမန-ဂမန",
      "KaTaLa-ကတလ-ကတလ",
      "KaPhaNa-ကဖန-ကဖန",
      "KaTaNa-ကတန-ကတန",
      "MaMaNa-မမန-မမန",
      "MaTaNa-မတန-မတန",
      "TaPaWa-တပဝ-တပဝ",
      "MaAuNa-မဥန-မဥန",
      "MaPaNa-မပန-မပန",
      "PaTaNa-ပတန-ပတန",
      "PaNaKa-ပဏက-ပဏက",
      "YaBaNa-ရဗန-ရဗန",
      "YaThaTa-ရသတ-ရသတ",
      "YaTaNa-ရတန-ရတန",
      "MaPaTa-မပတ-မပတ",
      "YaTaTha-ရတသ-ရတသ",
      "LaMaTa-လမတ-လမတ",
      "SaTaNa-စတန-စတန",
      "ThaTaNa-သတန-သတန",
      "MaAhNa-မအန-မအန",
      "TaKaNa-တကန-တကန",
      "MaATa-မအတ-မအတ"
    ]
  },
  {
    "regionCode": "12-၁၂-၁၂",
    "townships": [
      "AhLaNa-အလန-အလန",
      "BaHaNa-ဗဟန-ဗဟန",
      "BaTaHta-ဗတထ-ဗတထ",
      "KaKaKa-ကကက-ကကက",
      "DaGaNa-ဒဂန-ဒဂန",
      "DaGaSa-ဒဂဆ-ဒဂဆ",
      "DaLaNa-ဒလန-ဒလန",
      "DaPaNa-ဒပန-ဒပန",
      "DaGaYa-ဒဂရ-ဒဂရ",
      "LaMaNa-လမန-လမန",
      "LaThaYa-လသယ-လသယ",
      "LaKaNa-လကန-လကန",
      "MaBaNa-မဘန-မဘန",
      "HtaTaPa-ထတပ-ထတပ",
      "AhSaNa-အစန-အစန",
      "KaMaYa-ကမရ-ကမရ",
      "SaKaKha-ဆကခ-ဆကခ",
      "KaMaNa-ကမန-ကမန",
      "KhaYaNa-ခရန-ခရန",
      "KaKhaKa-ကခက-ကခက",
      "KaTaTa-ကတတ-ကတတ",
      "KaTaNa-ကတန-ကတန",
      "KaMaTa-ကမတ-ကမတ",
      "LaMaTa-လမတ-လမတ",
      "LaThaNa-လသန-လသန",
      "MaYaKa-မရက-မရက",
      "MaGaDa-မဂဒ-မဂဒ",
      "MaGaTa-မဂတ-မဂတ",
      "DaGaMa-ဒဂမ-ဒဂမ",
      "MaAuKa-မဥက-မဥက",
      "AuKaMa-ဥကမ-ဥကမ",
      "PaBaTa-ပဘတ-ပဘတ",
      "PaZaTa-ပဇတ-ပဇတ",
      "SaKhaNa-စခန-စခန",
      "SaKaNa-ဆကန-ဆကန",
      "YaPaTha-ရပသ-ရပသ",
      "DaGaTa-ဒဂတ-ဒဂတ",
      "AuKaTa-ဥကတ-ဥကတ",
      "TaAuKa-တဥက-တဥက",
      "TaKaNa-တကန-တကန",
      "TaMaNa-တမန-တမန",
      "ThaKaTa-သကတ-သကတ",
      "ThaLaNa-သလန-သလန",
      "ThaGaKa-သဃက-သဃက",
      "ThaKhaNa-သခန-သခန",
      "TaTaNa-တတန-တတန",
      "YaKaNa-ရကန-ရကန",
      "TaTaTa-တတတ-တတတ"
    ]
  },
  {
    "regionCode": "13-၁၃-၁၃",
    "townships": [
      "MaMaNa-မမန-မမန",
      "MaPaNa-မပန-မပန",
      "HaPaNa-ဟပန-ဟပန",
      "ThaNaNa-သနန-သနန",
      "SaSaNa-ဆဆန-ဆဆန",
      "ThaPaNa-သပန-သပန",
      "KaLaNa-ကလန-ကလန",
      "KaTaNa-ကတန-ကတန",
      "KaKaNa-ကကန-ကကန",
      "MaHtaTa-မထတ-မထတ",
      "KaHaNa-ကဟန-ကဟန",
      "KaKhaNa-ကခန-ကခန",
      "TaMaNya-တမည-တမည",
      "KaMaNa-ကမန-ကမန",
      "MaNgaNa-မငန-မငန",
      "KaThaNa-ကသန-ကသန",
      "LaKhaNa-လခန-လခန",
      "HaMaNa-ဟမန-ဟမန",
      "LaYaNa-လရန-လရန",
      "KhaYaHa-ခရဟ-ခရဟ",
      "LaKaNa-လကန-လကန",
      "YaSaNa-ရစန-ရစန",
      "LaLaNa-လလန-လလန",
      "MaBaNa-မဘန-မဘန",
      "MaTaNa-မတန-မတန",
      "MaKhaTa-မခတ-မခတ",
      "MaSaNa-မဆန-မဆန",
      "MaPhaTa-မဖတ-မဖတ",
      "MaPhaNa-မဖန-မဖန",
      "MaLaNa-မလန-မလန",
      "MaNaNa-မနန-မနန",
      "TaTaNa-တတန-တတန",
      "PaPaKa-ပပက-ပပက",
      "MaYaTa-မရတ-မရတ",
      "MaYaNa-မယန-မယန",
      "MaHaYa-မဟရ-မဟရ",
      "MaKaNa-မကန-မကန",
      "MaSaTa-မဆတ-မဆတ",
      "WaKaNa-ဝကန-ဝကန",
      "NaKhaNa-နခန-နခန",
      "NaSaNa-နစန-နစန",
      "NaHsaNa-နဆန-နဆန",
      "NaPhaNa-နဖန-နဖန",
      "KhaLaNa-ခလန-ခလန",
      "NaTaNa-နတန-နတန",
      "NaMaTa-နမတ-နမတ",
      "NyaYaNa-ညရန-ညရန",
      "MaKhaNa-မခန-မခန",
      "PaSaNa-ပဆန-ပဆန",
      "PaWaNa-ပဝန-ပဝန",
      "PhaKhaNa-ဖခန-ဖခန",
      "PaTaYa-ပတယ-ပတယ",
      "PaLaNa-ပလန-ပလန",
      "TaKhaLa-တခလ-တခလ",
      "TaYaNa-တယန-တယန",
      "TaKaNa-တကန-တကန",
      "KaTaLa-ကတလ-ကတလ",
      "YaNyaNa-ရညန-ရညန",
      "YaNgaNa-ရငန-ရငန",
      "AaPaNa-အပန-အပန",
      "AaThaYa-အသရ-အသရ",
      "AhTaNa-အတန-အတန",
      "TaLaNa-တလန-တလန",
      "NaTaRa-နတရ-နတရ",
      "PaLaTa-ပလတ-ပလတ",
      "KaLaDa-ကလဒ-ကလဒ",
      "LaKhaTa-လခတ-လခတ",
      "PaYaNa-ပယန-ပယန",
      "MaKaHta-မကထ-မကထ",
      "PaHsaTa-ပဆတ-ပဆတ",
      "NaKhaTa-နခတ-နခတ",
      "MaTaTa-မတတ-မတတ",
      "MaLaTa-မလတ-မလတ",
      "MaMaTa-မမတ-မမတ",
      "HaPaTa-ဟပတ-ဟပတ",
      "MaMaHta-မမထ-မမထ",
      "PaLaHta-ပလထ-ပလထ",
      "MaPaHta-မပထ-မပထ",
      "MaYaTa-မယတ-မယတ",
      "MaYaHta-မယထ-မယထ",
      "KaTaTa-ကတတ-ကတတ",
      "MaNaTa-မနတ-မနတ"
    ]
  },
  {
    "regionCode": "14-၁၄-၁၄",
    "townships": [
      "BaKaLa-ဘကလ-ဘကလ",
      "DaNaPha-ဓနဖ-ဓနဖ",
      "DaDaYa-ဒဒရ-ဒဒရ",
      "KaMaNa-ကမန-ကမန",
      "PaKaKha-ပကခ-ပကခ",
      "HaThaTa-ဟသတ-ဟသတ",
      "AhGaPa-အဂပ-အဂပ",
      "TaMaNa-တမန-တမန",
      "KaKaHta-ကကထ-ကကထ",
      "KaLaNa-ကလန-ကလန",
      "KaKhaNa-ကခန-ကခန",
      "KaKaNa-ကကန-ကကန",
      "KaPaNa-ကပန-ကပန",
      "LaPaTa-လပတ-လပတ",
      "PaSaLa-ပစလ-ပစလ",
      "LaMaNa-လမန-လမန",
      "MaAhPa-မအပ-မအပ",
      "MaMaKa-မမက-မမက",
      "MaAhNa-မအန-မအန",
      "AhPaNa-အပန-အပန",
      "MaMaNa-မမန-မမန",
      "HaKaKa-ဟကက-ဟကက",
      "NgaPaTa-ငပတ-ငပတ",
      "NgaYaKa-ငရက-ငရက",
      "NyaTaNa-ညတန-ညတန",
      "PaTaNa-ပတန-ပတန",
      "YaThaYa-ရသယ-ရသယ",
      "MaYaKa-မရက-မရက",
      "AhSaNa-အစန-အစန",
      "PaThaYa-ပသရ-ပသရ",
      "PaThaNa-ပသန-ပသန",
      "NgaSaNa-ငဆန-ငဆန",
      "AhMaNa-အမန-အမန",
      "KaMaTha-ကမသ-ကမသ",
      "PhaPaNa-ဖပန-ဖပန",
      "ThaPaNa-သပန-သပန",
      "WaKhaMa-ဝခမ-ဝခမ",
      "YaKaNa-ရကန-ရကန",
      "NgaThaKha-ငသခ-ငသခ",
      "ZaLaNa-ဇလန-ဇလန",
      "AMaTa-အမတ-အမတ"
    ]
  }
]

export const NRC_DATA:NRC[]=[
  {
      "regionCode": "1",
      "townships": [
          "BaKaNa",
          "BaMaNa",
          "PaMaNa",
          "AhTaNa",
          "MaTaNa",
          "KhaPhaNa",
          "TaNaNa",
          "PhaKaNa",
          "KaMaNa",
          "KhaLaPha",
          "MaKhaBa",
          "MaSaNa",
          "MaKaTa",
          "MaNyaNa",
          "HaPaNa",
          "MaKaTha",
          "MaMaNa",
          "MaKaNa",
          "SaKaNa",
          "KaMaTa",
          "SaBaTa",
          "SaPaBa",
          "MaGaDa",
          "AhGaYa",
          "NaMaNa",
          "PaTaAh",
          "YaKaNa",
          "SaBaNa",
          "SaLaNa",
          "WaMaNa",
          "HsaDaNa",
          "RaBaYa",
          "LaGaNa",
          "PaNaDa",
          "KhaBaDa",
          "HsaPaBa",
          "DaPhaYa",
          "MaLaNa"
      ]
  },
  {
      "regionCode": "2",
      "townships": [
          "BaLaKha",
          "DaMaSa",
          "SaSaNa",
          "HtaTaPa",
          "KhaSaNa",
          "PhaLaSa",
          "PhaYaSa",
          "LaKaNa",
          "MaSaNa",
          "YaTaNa",
          "HpaHsaNa",
          "RaThaNa"
      ]
  },
  {
      "regionCode": "3",
      "townships": [
          "LaBaNa",
          "PaKaNa",
          "YaYaTha",
          "PhaAhNa",
          "BaAhNa",
          "PhaPaNa",
          "KaMaMa",
          "KaKaYa",
          "KaDaNa",
          "KaSaKa",
          "MaWaTa",
          "SaKaLa",
          "MaSaLa",
          "KaTaKha",
          "WaLaMa",
          "BaGaLa",
          "LaThaNa",
          "ThaTaNa",
          "ThaTaKa",
          "BaThaHsa"
      ]
  },
  {
      "regionCode": "4",
      "townships": [
          "HpaLaNa",
          "HaKhaNa",
          "KaPaLa",
          "MaTaPa",
          "MaTaNa",
          "PaLaWa",
          "TaTaNa",
          "HtaTaLa",
          "TaZaNa",
          "RaKhaDa",
          "RaZaNa",
          "HsaMaNa",
          "KaKhaNa"
      ]
  },
  {
      "regionCode": "5",
      "townships": [
          "AhYaTa",
          "BaMaNa",
          "BaTaLa",
          "KhaAuNa",
          "KhaTaNa",
          "HaMaLa",
          "AhTaNa",
          "KaLaNa",
          "KaLaHta",
          "KaLaWa",
          "KaBaLa",
          "AhHtaNa",
          "KaNaNa",
          "KaThaNa",
          "KaLaTa",
          "KaSaLa",
          "HtaPaKha",
          "LaHaNa",
          "LaYaNa",
          "MaPaLa",
          "SaMaYa",
          "MaLaNa",
          "MaKaNa",
          "MaYaNa",
          "MaMaNa",
          "DaHaNa",
          "NaYaNa",
          "PaSaNa",
          "PaLaNa",
          "PhaPaNa",
          "PaLaBa",
          "SaKaNa",
          "SaLaKa",
          "KaMaNa",
          "YaBaNa",
          "DaPaYa",
          "TaMaNa",
          "MaThaNa",
          "TaSaNa",
          "HtaKhaNa",
          "KaLaTha",
          "NgaSaNa",
          "TaAuNa",
          "DaKaNa",
          "AhMaZa",
          "WaLaNa",
          "WaThaNa",
          "YaAuNa",
          "YaMaPa",
          "MaMaTa",
          "KhaUTa",
          "KhaPaNa"
      ]
  },
  {
      "regionCode": "6",
      "townships": [
          "BaPaNa",
          "HtaWaNa",
          "AhMaYa",
          "KaYaYa",
          "KaPaNa",
          "KaThaMa",
          "HaThaTa",
          "KhaMaKa",
          "MaMaLa",
          "KaThaNa",
          "KaSaNa",
          "MaAhNa",
          "LaLaNa",
          "MaMaNa",
          "MaAhYa",
          "PhaLaNa",
          "TaThaYa",
          "ThaYaKha",
          "YaPhaNa",
          "KaLaA",
          "PaLaTa",
          "PaKaMa"
      ]
  },
  {
      "regionCode": "7",
      "townships": [
          "PaKhaNa",
          "MaWaTa",
          "DaAuNa",
          "KaPaKa",
          "HtaTaPa",
          "KaWaNa",
          "KaKaNa",
          "KaTaKha",
          "KaTaNa",
          "LaPaTa",
          "MaLaNa",
          "MaNyaNa",
          "NaTaLa",
          "NyaLaPa",
          "AhPhaNa",
          "AhTaNa",
          "PaTaNa",
          "PaKhaTa",
          "PaTaTa",
          "PhaMaNa",
          "PaSaTa",
          "PaMaNa",
          "YaTaNa",
          "YaKaNa",
          "TaNgaNa",
          "ThaNaPa",
          "ThaWaTa",
          "ThaKaNa",
          "WaMaNa",
          "YaTaYa",
          "ZaKaNa",
          "BaThaYa"
      ]
  },
  {
      "regionCode": "8",
      "townships": [
          "AhLaNa",
          "MaHtaNa",
          "KhaMaNa",
          "BaKaLa",
          "GaGaNa",
          "KaMaNa",
          "MaKaNa",
          "MaBaNa",
          "MaTaNa",
          "MaLaNa",
          "MaMaNa",
          "MaThaNa",
          "NaMaNa",
          "NgaPhaNa",
          "PaKhaKa",
          "PaMaNa",
          "PaPhaNa",
          "SaLaNa",
          "KaHtaNa",
          "SaPhaNa",
          "SaTaYa",
          "SaPaWa",
          "MaYaSa",
          "MaGaDa",
          "MaHtaLa",
          "TaTaKa",
          "ThaYaNa",
          "HtaLaNa",
          "YaNaKha",
          "YaSaKa",
          "HsaMaNa"
      ]
  },
  {
      "regionCode": "9",
      "townships": [
          "AhMaYa",
          "KhaMaSa",
          "KhaMaKha",
          "AhYaTa",
          "ThaTaYa",
          "KhaMaZa",
          "NaNaMa",
          "PaKhaMa",
          "KaMaNa",
          "AhMaZa",
          "MaNaMa",
          "KhaAhZa",
          "KhaMaTha",
          "KaPaTa",
          "KhaMaNa",
          "KaSaNa",
          "NaTaKa",
          "SaKaTa",
          "MaSaNa",
          "LaKaNa",
          "YaAuNa",
          "MaYaTa",
          "MaTaNa",
          "MaTaYa",
          "MaHaMa",
          "MaLaNa",
          "MaHtaLa",
          "MaKaNa",
          "MaKhaNa",
          "MaThaNa",
          "NaMaNa",
          "MaTaLa",
          "NaHtaKa",
          "NgaZaNa",
          "NyaAuNa",
          "AhKhaNa",
          "PaThaKa",
          "PaBaNa",
          "PaKaKha",
          "AhMaBa",
          "AhSaNa",
          "KhaMaMa",
          "MaKaKha",
          "MaNaTa",
          "MaYaMa",
          "PaKhaKa",
          "ThaWaNa",
          "PaAuLa",
          "MaMaNa",
          "SaKaNa",
          "TaTaAu",
          "TaThaNa",
          "ThaPaKa",
          "ThaSaNa",
          "WaTaNa",
          "YaMaTha",
          "DaKhaTha",
          "LaWaNa",
          "AuTaTha",
          "PaBaTha",
          "PaMaNa",
          "TaKaNa",
          "ZaBaTha",
          "ZaYaTha",
          "TaKaTa",
          "NgaThaRa"
      ]
  },
  {
      "regionCode": "10",
      "townships": [
          "BaLaNa",
          "KhaSaNa",
          "KaMaYa",
          "BaAhNa",
          "KaHtaNa",
          "HtaHtaNa",
          "KaMaLa",
          "PhaPaNa",
          "MaSaNa",
          "MaLaMa",
          "MaDaNa",
          "PaMaNa",
          "ThaPhaYa",
          "ThaHtaNa",
          "KhaZaNa",
          "LaMaNa",
          "YaMaNa"
      ]
  },
  {
      "regionCode": "11",
      "townships": [
          "AhMaNa",
          "BaThaTa",
          "GaMaNa",
          "KaTaLa",
          "KaPhaNa",
          "KaTaNa",
          "MaMaNa",
          "MaTaNa",
          "TaPaWa",
          "MaAuNa",
          "MaPaNa",
          "PaTaNa",
          "PaNaKa",
          "YaBaNa",
          "YaThaTa",
          "YaTaNa",
          "MaPaTa",
          "YaTaTha",
          "LaMaTa",
          "SaTaNa",
          "ThaTaNa",
          "MaAhNa",
          "TaKaNa",
          "MaATa"
      ]
  },
  {
      "regionCode": "12",
      "townships": [
          "AhLaNa",
          "BaHaNa",
          "BaTaHta",
          "KaKaKa",
          "DaGaNa",
          "DaGaSa",
          "DaLaNa",
          "DaPaNa",
          "DaGaYa",
          "LaMaNa",
          "LaThaYa",
          "LaKaNa",
          "MaBaNa",
          "HtaTaPa",
          "AhSaNa",
          "KaMaYa",
          "SaKaKha",
          "KaMaNa",
          "KhaYaNa",
          "KaKhaKa",
          "KaTaTa",
          "KaTaNa",
          "KaMaTa",
          "LaMaTa",
          "LaThaNa",
          "MaYaKa",
          "MaGaDa",
          "MaGaTa",
          "DaGaMa",
          "MaAuKa",
          "AuKaMa",
          "PaBaTa",
          "PaZaTa",
          "SaKhaNa",
          "SaKaNa",
          "YaPaTha",
          "DaGaTa",
          "AuKaTa",
          "TaAuKa",
          "TaKaNa",
          "TaMaNa",
          "ThaKaTa",
          "ThaLaNa",
          "ThaGaKa",
          "ThaKhaNa",
          "TaTaNa",
          "YaKaNa",
          "TaTaTa"
      ]
  },
  {
      "regionCode": "13",
      "townships": [
          "MaMaNa",
          "MaPaNa",
          "HaPaNa",
          "ThaNaNa",
          "SaSaNa",
          "ThaPaNa",
          "KaLaNa",
          "KaTaNa",
          "KaKaNa",
          "MaHtaTa",
          "KaHaNa",
          "KaKhaNa",
          "TaMaNya",
          "KaMaNa",
          "MaNgaNa",
          "KaThaNa",
          "LaKhaNa",
          "HaMaNa",
          "LaYaNa",
          "KhaYaHa",
          "LaKaNa",
          "YaSaNa",
          "LaLaNa",
          "MaBaNa",
          "MaTaNa",
          "MaKhaTa",
          "MaSaNa",
          "MaPhaTa",
          "MaPhaNa",
          "MaLaNa",
          "MaNaNa",
          "TaTaNa",
          "PaPaKa",
          "MaYaTa",
          "MaYaNa",
          "MaHaYa",
          "MaKaNa",
          "MaSaTa",
          "WaKaNa",
          "NaKhaNa",
          "NaSaNa",
          "NaHsaNa",
          "NaPhaNa",
          "KhaLaNa",
          "NaTaNa",
          "NaMaTa",
          "NyaYaNa",
          "MaKhaNa",
          "PaSaNa",
          "PaWaNa",
          "PhaKhaNa",
          "PaTaYa",
          "PaLaNa",
          "TaKhaLa",
          "TaYaNa",
          "TaKaNa",
          "KaTaLa",
          "YaNyaNa",
          "YaNgaNa",
          "AaPaNa",
          "AaThaYa",
          "AhTaNa",
          "TaLaNa",
          "NaTaRa",
          "PaLaTa",
          "KaLaDa",
          "LaKhaTa",
          "PaYaNa",
          "MaKaHta",
          "PaHsaTa",
          "NaKhaTa",
          "MaTaTa",
          "MaLaTa",
          "MaMaTa",
          "HaPaTa",
          "MaMaHta",
          "PaLaHta",
          "MaPaHta",
          "MaYaTa",
          "MaYaHta",
          "KaTaTa",
          "MaNaTa"
      ]
  },
  {
      "regionCode": "14",
      "townships": [
          "BaKaLa",
          "DaNaPha",
          "DaDaYa",
          "KaMaNa",
          "PaKaKha",
          "HaThaTa",
          "AhGaPa",
          "TaMaNa",
          "KaKaHta",
          "KaLaNa",
          "KaKhaNa",
          "KaKaNa",
          "KaPaNa",
          "LaPaTa",
          "PaSaLa",
          "LaMaNa",
          "MaAhPa",
          "MaMaKa",
          "MaAhNa",
          "AhPaNa",
          "MaMaNa",
          "HaKaKa",
          "NgaPaTa",
          "NgaYaKa",
          "NyaTaNa",
          "PaTaNa",
          "YaThaYa",
          "MaYaKa",
          "AhSaNa",
          "PaThaYa",
          "PaThaNa",
          "NgaSaNa",
          "AhMaNa",
          "KaMaTha",
          "PhaPaNa",
          "ThaPaNa",
          "WaKhaMa",
          "YaKaNa",
          "NgaThaKha",
          "ZaLaNa",
          "AMaTa"
      ]
  },
  // {
  //     "regionCode": "၁",
  //     "townships": [
  //         "ဗကန",
  //         "ဘမန",
  //         "ပမန",
  //         "အတန",
  //         "မတန",
  //         "ခဖန",
  //         "တနန",
  //         "ဖကန",
  //         "ကမန",
  //         "ခလဖ",
  //         "မခဘ",
  //         "မစန",
  //         "မကတ",
  //         "မညန",
  //         "ဟပန",
  //         "မကသ",
  //         "မမန",
  //         "မကန",
  //         "စကန",
  //         "ကမတ",
  //         "ဆဘတ",
  //         "စပဘ",
  //         "မဂဒ",
  //         "အဂယ",
  //         "နမန",
  //         "ပတအ",
  //         "ရကန",
  //         "ဆဘန",
  //         "ဆလန",
  //         "ဝမန",
  //         "ဆဒန",
  //         "ရဗယ",
  //         "လဂန",
  //         "ပနဒ",
  //         "ခဘဒ",
  //         "ဆပဘ",
  //         "ဒဖယ",
  //         "မလန"
  //     ]
  // },
  // {
  //     "regionCode": "၂",
  //     "townships": [
  //         "ဘလခ",
  //         "ဒမဆ",
  //         "စစန",
  //         "ထတပ",
  //         "ခစန",
  //         "ဖလဆ",
  //         "ဖရဆ",
  //         "လကန",
  //         "မဆန",
  //         "ရတန",
  //         "ဖဆန",
  //         "ရသန"
  //     ]
  // },
  // {
  //     "regionCode": "၃",
  //     "townships": [
  //         "လဘန",
  //         "ပကန",
  //         "ရရသ",
  //         "ဖအန",
  //         "ဘအန",
  //         "ဖပန",
  //         "ကမမ",
  //         "ကကရ",
  //         "ကဒန",
  //         "ကဆက",
  //         "မဝတ",
  //         "စကလ",
  //         "မဆလ",
  //         "ကတခ",
  //         "ဝလမ",
  //         "ဘဂလ",
  //         "လသန",
  //         "သတန",
  //         "သတက",
  //         "ဘသဆ"
  //     ]
  // },
  // {
  //     "regionCode": "၄",
  //     "townships": [
  //         "ဖလန",
  //         "ဟခန",
  //         "ကပလ",
  //         "မတပ",
  //         "မတန",
  //         "ပလဝ",
  //         "တတန",
  //         "ထတလ",
  //         "တဇန",
  //         "ရခဒ",
  //         "ရဇန",
  //         "ဆမန",
  //         "ကခန"
  //     ]
  // },
  // {
  //     "regionCode": "၅",
  //     "townships": [
  //         "အရတ",
  //         "ဗမန",
  //         "ဘတလ",
  //         "ခဥန",
  //         "ခတန",
  //         "ဟမလ",
  //         "အတန",
  //         "ကလန",
  //         "ကလထ",
  //         "ကလဝ",
  //         "ကဘလ",
  //         "အထန",
  //         "ကနန",
  //         "ကသန",
  //         "ကလတ",
  //         "ကဆလ",
  //         "ထပခ",
  //         "လဟန",
  //         "လရန",
  //         "မပလ",
  //         "ဆမရ",
  //         "မလန",
  //         "မကန",
  //         "မရန",
  //         "မမန",
  //         "ဒဟန",
  //         "နယန",
  //         "ပဆန",
  //         "ပလန",
  //         "ဖပန",
  //         "ပလဘ",
  //         "စကန",
  //         "ဆလက",
  //         "ကမန",
  //         "ရဘန",
  //         "ဒပယ",
  //         "တမန",
  //         "မသန",
  //         "တဆန",
  //         "ထခန",
  //         "ကလသ",
  //         "ငစန",
  //         "တဥန",
  //         "ဓကန",
  //         "အမဇ",
  //         "ဝလန",
  //         "ဝသန",
  //         "ရဥန",
  //         "ယမပ",
  //         "မမတ",
  //         "ခဥတ",
  //         "ခပန"
  //     ]
  // },
  // {
  //     "regionCode": "၆",
  //     "townships": [
  //         "ဘပန",
  //         "ထဝန",
  //         "အမရ",
  //         "ကရရ",
  //         "ကပန",
  //         "ကသမ",
  //         "ဟသတ",
  //         "ခမက",
  //         "မမလ",
  //         "ကသန",
  //         "ကစန",
  //         "မအန",
  //         "လလန",
  //         "မမန",
  //         "မအရ",
  //         "ပလန",
  //         "တသရ",
  //         "သရခ",
  //         "ရဖန",
  //         "ကလအ",
  //         "ပလတ",
  //         "ပကမ"
  //     ]
  // },
  // {
  //     "regionCode": "၇",
  //     "townships": [
  //         "ပခန",
  //         "မဝတ",
  //         "ဒဥန",
  //         "ကပက",
  //         "ထတပ",
  //         "ကဝန",
  //         "ကကန",
  //         "ကတခ",
  //         "ကတန",
  //         "လပတ",
  //         "မလန",
  //         "မညန",
  //         "နတလ",
  //         "ညလပ",
  //         "အဖန",
  //         "အတန",
  //         "ပတန",
  //         "ပခတ",
  //         "ပတတ",
  //         "ဖမန",
  //         "ပစတ",
  //         "ပမန",
  //         "ရတန",
  //         "ရကန",
  //         "တငန",
  //         "သနပ",
  //         "သဝတ",
  //         "သကန",
  //         "ဝမန",
  //         "ရတရ",
  //         "ဇကန",
  //         "ဘသရ"
  //     ]
  // },
  // {
  //     "regionCode": "၈",
  //     "townships": [
  //         "အလန",
  //         "မထန",
  //         "ခမန",
  //         "ဘကလ",
  //         "ဂဂန",
  //         "ကမန",
  //         "မကန",
  //         "မဘန",
  //         "မတန",
  //         "မလန",
  //         "မမန",
  //         "မသန",
  //         "နမန",
  //         "ငဖန",
  //         "ပခက",
  //         "ပမန",
  //         "ပဖန",
  //         "စလန",
  //         "ကထန",
  //         "ဆဖန",
  //         "စတရ",
  //         "ဆပဝ",
  //         "မရဆ",
  //         "မဂဒ",
  //         "မထလ",
  //         "တတက",
  //         "သရန",
  //         "ထလန",
  //         "ရနခ",
  //         "ရစက",
  //         "ဆမန"
  //     ]
  // },
  // {
  //     "regionCode": "၉",
  //     "townships": [
  //         "အမရ",
  //         "ခမစ",
  //         "ခမခ",
  //         "အရတ",
  //         "သတရ",
  //         "ခမဇ",
  //         "နနမ",
  //         "ပခမ",
  //         "ကမန",
  //         "အမဇ",
  //         "မနမ",
  //         "ခအဇ",
  //         "ခမသ",
  //         "ကပတ",
  //         "ခမန",
  //         "ကဆန",
  //         "နတက",
  //         "စကတ",
  //         "မစန",
  //         "လကန",
  //         "ရဥန",
  //         "မရတ",
  //         "မတန",
  //         "မတရ",
  //         "မဟမ",
  //         "မလန",
  //         "မထလ",
  //         "မကန",
  //         "မခန",
  //         "မသန",
  //         "နမန",
  //         "မတလ",
  //         "နထက",
  //         "ငဇန",
  //         "ညဥန",
  //         "အခန",
  //         "ပသက",
  //         "ပဘန",
  //         "ပကခ",
  //         "အမဘ",
  //         "အစန",
  //         "ခမမ",
  //         "မကခ",
  //         "မနတ",
  //         "မရမ",
  //         "ပခက",
  //         "သဝန",
  //         "ပဥလ",
  //         "မမန",
  //         "စကန",
  //         "တတဥ",
  //         "တသန",
  //         "သပက",
  //         "သစန",
  //         "ဝတန",
  //         "ရမသ",
  //         "ဒခသ",
  //         "လဝန",
  //         "ဥတသ",
  //         "ပဗသ",
  //         "ပမန",
  //         "တကန",
  //         "ဇဗသ",
  //         "ဇယသ",
  //         "တကတ",
  //         "ငသရ"
  //     ]
  // },
  // {
  //     "regionCode": "၁၀",
  //     "townships": [
  //         "ဘလန",
  //         "ခဆန",
  //         "ကမရ",
  //         "ဘအန",
  //         "ကထန",
  //         "ထထန",
  //         "ကမလ",
  //         "ဖပန",
  //         "မစန",
  //         "မလမ",
  //         "မဒန",
  //         "ပမန",
  //         "သဖရ",
  //         "သထန",
  //         "ခဇန",
  //         "လမန",
  //         "ရမန"
  //     ]
  // },
  // {
  //     "regionCode": "၁၁",
  //     "townships": [
  //         "အမန",
  //         "ဘသတ",
  //         "ဂမန",
  //         "ကတလ",
  //         "ကဖန",
  //         "ကတန",
  //         "မမန",
  //         "မတန",
  //         "တပဝ",
  //         "မဥန",
  //         "မပန",
  //         "ပတန",
  //         "ပဏက",
  //         "ရဗန",
  //         "ရသတ",
  //         "ရတန",
  //         "မပတ",
  //         "ရတသ",
  //         "လမတ",
  //         "စတန",
  //         "သတန",
  //         "မအန",
  //         "တကန",
  //         "မအတ"
  //     ]
  // },
  // {
  //     "regionCode": "၁၂",
  //     "townships": [
  //         "အလန",
  //         "ဗဟန",
  //         "ဗတထ",
  //         "ကကက",
  //         "ဒဂန",
  //         "ဒဂဆ",
  //         "ဒလန",
  //         "ဒပန",
  //         "ဒဂရ",
  //         "လမန",
  //         "လသယ",
  //         "လကန",
  //         "မဘန",
  //         "ထတပ",
  //         "အစန",
  //         "ကမရ",
  //         "ဆကခ",
  //         "ကမန",
  //         "ခရန",
  //         "ကခက",
  //         "ကတတ",
  //         "ကတန",
  //         "ကမတ",
  //         "လမတ",
  //         "လသန",
  //         "မရက",
  //         "မဂဒ",
  //         "မဂတ",
  //         "ဒဂမ",
  //         "မဥက",
  //         "ဥကမ",
  //         "ပဘတ",
  //         "ပဇတ",
  //         "စခန",
  //         "ဆကန",
  //         "ရပသ",
  //         "ဒဂတ",
  //         "ဥကတ",
  //         "တဥက",
  //         "တကန",
  //         "တမန",
  //         "သကတ",
  //         "သလန",
  //         "သဃက",
  //         "သခန",
  //         "တတန",
  //         "ရကန",
  //         "တတတ"
  //     ]
  // },
  // {
  //     "regionCode": "၁၃",
  //     "townships": [
  //         "မမန",
  //         "မပန",
  //         "ဟပန",
  //         "သနန",
  //         "ဆဆန",
  //         "သပန",
  //         "ကလန",
  //         "ကတန",
  //         "ကကန",
  //         "မထတ",
  //         "ကဟန",
  //         "ကခန",
  //         "တမည",
  //         "ကမန",
  //         "မငန",
  //         "ကသန",
  //         "လခန",
  //         "ဟမန",
  //         "လရန",
  //         "ခရဟ",
  //         "လကန",
  //         "ရစန",
  //         "လလန",
  //         "မဘန",
  //         "မတန",
  //         "မခတ",
  //         "မဆန",
  //         "မဖတ",
  //         "မဖန",
  //         "မလန",
  //         "မနန",
  //         "တတန",
  //         "ပပက",
  //         "မရတ",
  //         "မယန",
  //         "မဟရ",
  //         "မကန",
  //         "မဆတ",
  //         "ဝကန",
  //         "နခန",
  //         "နစန",
  //         "နဆန",
  //         "နဖန",
  //         "ခလန",
  //         "နတန",
  //         "နမတ",
  //         "ညရန",
  //         "မခန",
  //         "ပဆန",
  //         "ပဝန",
  //         "ဖခန",
  //         "ပတယ",
  //         "ပလန",
  //         "တခလ",
  //         "တယန",
  //         "တကန",
  //         "ကတလ",
  //         "ရညန",
  //         "ရငန",
  //         "အပန",
  //         "အသရ",
  //         "အတန",
  //         "တလန",
  //         "နတရ",
  //         "ပလတ",
  //         "ကလဒ",
  //         "လခတ",
  //         "ပယန",
  //         "မကထ",
  //         "ပဆတ",
  //         "နခတ",
  //         "မတတ",
  //         "မလတ",
  //         "မမတ",
  //         "ဟပတ",
  //         "မမထ",
  //         "ပလထ",
  //         "မပထ",
  //         "မယတ",
  //         "မယထ",
  //         "ကတတ",
  //         "မနတ"
  //     ]
  // },
  // {
  //     "regionCode": "၁၄",
  //     "townships": [
  //         "ဘကလ",
  //         "ဓနဖ",
  //         "ဒဒရ",
  //         "ကမန",
  //         "ပကခ",
  //         "ဟသတ",
  //         "အဂပ",
  //         "တမန",
  //         "ကကထ",
  //         "ကလန",
  //         "ကခန",
  //         "ကကန",
  //         "ကပန",
  //         "လပတ",
  //         "ပစလ",
  //         "လမန",
  //         "မအပ",
  //         "မမက",
  //         "မအန",
  //         "အပန",
  //         "မမန",
  //         "ဟကက",
  //         "ငပတ",
  //         "ငရက",
  //         "ညတန",
  //         "ပတန",
  //         "ရသယ",
  //         "မရက",
  //         "အစန",
  //         "ပသရ",
  //         "ပသန",
  //         "ငဆန",
  //         "အမန",
  //         "ကမသ",
  //         "ဖပန",
  //         "သပန",
  //         "ဝခမ",
  //         "ရကန",
  //         "ငသခ",
  //         "ဇလန",
  //         "အမတ"
  //     ]
  // }
]
