export const SUB_MENUS = {
  MANAGEMENTS: ["user-management", "role-management", "company-management"],
  BULK_UPLOADS: [
    "bulk-list",
    "bulk-upload-for-creation",
    "bulk-upload-for-modification",
  ],
  REPORTS: [
    "kyc-approval-reports",
    "kyc-rejection-reports",
    "kyc-pending-reports",
    "kyc-mobile-ac-reports",
    "kyc-otc-reports",
    "kyc-performance-reports",
    "kyc-status-summary",
    "generate-new-reports",
  ],
  OTCS: [
    "all-otc-profiles",
    "approved-otc-profiles",
    "pending-to-approve-otc-profiles",
    "pending-to-review-edited-otc-profiles",
    "pending-to-recommend-otc-profiles",
    "recommend-to-approve-otc-profiles",
    "recommend-to-reject-otc-profiles",
    "rejected-otc-profiles",
  ],
  SUBSCRIBERS: [
    "add-new-subscriber",
    "all-subscribers",
    "not-submitted-subscribers",
    "pending-to-approve-subscribers",
    "pending-to-recommend-subscribers",
    "recommend-to-approve-subscribers",
    "recommend-to-reject-subscribers",
    "approved-subscribers",
    "rejected-subscribers",
  ],
};
