import { ADMIN_API_BASE_URL } from "./env";
import {
  capitalize,
  titleCase,
  getFormattedDate,
  commaRemover,
  getDate,
  refreshPage,
  humanize,
  objectToFormData,
  setHeaderTitle,
  getAllCookies,
  avatarFormatter,
  getRole,
  getFilteredRoles,
  generateNrcNo,
  splitedNrcNo,
  splitedForeignData,
  getBase64,
  checkRoleBasedPermission,
  getUserPermissions,
  getStyledStatus,
  getOtcUrl
} from "./utils";

export {
  ADMIN_API_BASE_URL,
  capitalize,
  titleCase,
  getFormattedDate,
  commaRemover,
  getDate,
  refreshPage,
  humanize,
  objectToFormData,
  setHeaderTitle,
  getAllCookies,
  avatarFormatter,
  getRole,
  getFilteredRoles,
  generateNrcNo,
  splitedNrcNo,
  splitedForeignData,
  getBase64,
  checkRoleBasedPermission,
  getUserPermissions,
  getStyledStatus,
  getOtcUrl
};
